

/** Dictionary */
export const GET_PROCESS_LIST = "GET_PROCESS_LIST";
export const GET_MACHINE_TYPE_LIST = "GET_MACHINE_TYPE_LIST";
export const GET_USER_ROLE_LIST = "GET_USER_ROLE_LIST";
export const GET_OFFICE_LIST = "GET_OFFICE_LIST";
export const GET_SEX_LIST = "GET_SEX_LIST";
export const GET_PROVINCE_LIST = "GET_PROVINCE_LIST";
export const GET_DESIGN_SERIES_LIST = "GET_DESIGN_SERIES_LIST";

/** HomePage */
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";